# ==== Imports ==== #
from pathlib import Path
import os

# ==== Application Metadata ==== #
APP_NAME    = "MSFSDiag"
APP_VERSION = "1.0.0"

# ==== MSFS Paths ==== #
MSFS2020_APPDATA: Path = Path(os.environ["APPDATA"]) / "Microsoft Flight Simulator"
MSFS2024_APPDATA: Path = Path(os.environ["APPDATA"]) / "Microsoft Flight Simulator 2024"

# ==== Known Configuration Files ==== #
MSFS2020_USER_CFG: Path = MSFS2020_APPDATA / "UserCfg.opt"
MSFS2024_USER_CFG: Path = MSFS2024_APPDATA / "UserCfg.opt"

# ==== Add-ons Manifest ==== #
MANIFEST_FILENAME        = "manifest.json"
LAYOUT_FILENAME          = "layout.json"
REQUIRED_MANIFEST_FIELDS = [
    "title",
    "manufacturer",
    "version",
    "minimum_game_version",
    "content_type",
    "dependencies",
]

# ==== Languages ==== #
LANGUAGES = {
    "PT": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Menu Principal",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Registos de Eventos",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Definições",
        "run_diagnostic": "Executar Diagnóstico",
        "msfs_version":   "Versão MSFS",
        "community_path": "Community Folder",
        "no_addons":      "Nenhum add-on encontrado.",
        "addon_ok":       "OK",
        "addon_errors":   "Erros",
        "missing_fields": "Campos em falta",
        "invalid_json":   "JSON inválido",
        "no_events":      "Nenhum evento encontrado.",
        "no_symlinks":    "Nenhum symlink quebrado.",
        "theme":          "Tema",
        "language":       "Língua",
        "light":          "Claro",
        "dark":           "Escuro",
        "not_detected":   "Não detetado",
    },
    "EN": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Dashboard",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Event Logs",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Settings",
        "run_diagnostic": "Run Diagnostic",
        "msfs_version":   "MSFS Version",
        "community_path": "Community Folder",
        "no_addons":      "No add-ons found.",
        "addon_ok":       "OK",
        "addon_errors":   "Errors",
        "missing_fields": "Missing fields",
        "invalid_json":   "Invalid JSON",
        "no_events":      "No events found.",
        "no_symlinks":    "No broken symlinks.",
        "theme":          "Theme",
        "language":       "Language",
        "light":          "Light",
        "dark":           "Dark",
        "not_detected":   "Not detected",
    },
    "ES": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Dashboard",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Registros de eventos",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Ajustes",
        "run_diagnostic": "Ejecutar diagnóstico",
        "msfs_version":   "Versión MSFS",
        "community_path": "Carpeta Community",
        "no_addons":      "No se encontraron add-ons.",
        "addon_ok":       "OK",
        "addon_errors":   "Errores",
        "missing_fields": "Campos faltantes",
        "invalid_json":   "JSON inválido",
        "no_events":      "No se encontraron eventos.",
        "no_symlinks":    "No hay symlinks rotos.",
        "theme":          "Tema",
        "language":       "Idioma",
        "light":          "Claro",
        "dark":           "Oscuro",
        "not_detected":   "No detectado",
    },
    "FR": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Tableau de bord",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Journaux d'événements",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Paramètres",
        "run_diagnostic": "Lancer le diagnostic",
        "msfs_version":   "Version MSFS",
        "community_path": "Dossier Community",
        "no_addons":      "Aucun add-on trouvé.",
        "addon_ok":       "OK",
        "addon_errors":   "Erreurs",
        "missing_fields": "Champs manquants",
        "invalid_json":   "JSON invalide",
        "no_events":      "Aucun événement trouvé.",
        "no_symlinks":    "Aucun symlink cassé.",
        "theme":          "Thème",
        "language":       "Langue",
        "light":          "Clair",
        "dark":           "Sombre",
        "not_detected":   "Non détecté",
    },
    "DE": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Dashboard",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Ereignisprotokolle",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Einstellungen",
        "run_diagnostic": "Diagnose starten",
        "msfs_version":   "MSFS-Version",
        "community_path": "Community-Ordner",
        "no_addons":      "Keine Add-ons gefunden.",
        "addon_ok":       "OK",
        "addon_errors":   "Fehler",
        "missing_fields": "Fehlende Felder",
        "invalid_json":   "Ungültiges JSON",
        "no_events":      "Keine Ereignisse gefunden.",
        "no_symlinks":    "Keine defekten Symlinks.",
        "theme":          "Thema",
        "language":       "Sprache",
        "light":          "Hell",
        "dark":           "Dunkel",
        "not_detected":   "Nicht erkannt",
    },
    "IT": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Dashboard",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Registro eventi",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Impostazioni",
        "run_diagnostic": "Esegui diagnostica",
        "msfs_version":   "Versione MSFS",
        "community_path": "Cartella Community",
        "no_addons":      "Nessun add-on trovato.",
        "addon_ok":       "OK",
        "addon_errors":   "Errori",
        "missing_fields": "Campi mancanti",
        "invalid_json":   "JSON non valido",
        "no_events":      "Nessun evento trovato.",
        "no_symlinks":    "Nessun symlink rotto.",
        "theme":          "Tema",
        "language":       "Lingua",
        "light":          "Chiaro",
        "dark":           "Scuro",
        "not_detected":   "Non rilevato",
    },
    "NL": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Dashboard",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Gebeurtenislogboeken",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Instellingen",
        "run_diagnostic": "Diagnose uitvoeren",
        "msfs_version":   "MSFS-versie",
        "community_path": "Community-map",
        "no_addons":      "Geen add-ons gevonden.",
        "addon_ok":       "OK",
        "addon_errors":   "Fouten",
        "missing_fields": "Ontbrekende velden",
        "invalid_json":   "Ongeldige JSON",
        "no_events":      "Geen gebeurtenissen gevonden.",
        "no_symlinks":    "Geen gebroken symlinks.",
        "theme":          "Thema",
        "language":       "Taal",
        "light":          "Licht",
        "dark":           "Donker",
        "not_detected":   "Niet gedetecteerd",
    },
    "RU": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Панель",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Журнал событий",
        "tab_symlinks":   "Симлинки",
        "tab_settings":   "Настройки",
        "run_diagnostic": "Запустить диагностику",
        "msfs_version":   "Версия MSFS",
        "community_path": "Папка Community",
        "no_addons":      "Add-ons не найдены.",
        "addon_ok":       "OK",
        "addon_errors":   "Ошибки",
        "missing_fields": "Отсутствующие поля",
        "invalid_json":   "Неверный JSON",
        "no_events":      "События не найдены.",
        "no_symlinks":    "Сломанных симлинков нет.",
        "theme":          "Тема",
        "language":       "Язык",
        "light":          "Светлая",
        "dark":           "Тёмная",
        "not_detected":   "Не обнаружено",
    },
    "TR": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "Gösterge Paneli",
        "tab_addons":     "Add-ons",
        "tab_eventlogs":  "Olay Günlükleri",
        "tab_symlinks":   "Symlinks",
        "tab_settings":   "Ayarlar",
        "run_diagnostic": "Tanılamayı Çalıştır",
        "msfs_version":   "MSFS Sürümü",
        "community_path": "Community Klasörü",
        "no_addons":      "Add-on bulunamadı.",
        "addon_ok":       "OK",
        "addon_errors":   "Hatalar",
        "missing_fields": "Eksik alanlar",
        "invalid_json":   "Geçersiz JSON",
        "no_events":      "Olay bulunamadı.",
        "no_symlinks":    "Kırık symlink yok.",
        "theme":          "Tema",
        "language":       "Dil",
        "light":          "Açık",
        "dark":           "Koyu",
        "not_detected":   "Algılanmadı",
    },
    "ZH": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "仪表板",
        "tab_addons":     "插件",
        "tab_eventlogs":  "事件日志",
        "tab_symlinks":   "符号链接",
        "tab_settings":   "设置",
        "run_diagnostic": "运行诊断",
        "msfs_version":   "MSFS 版本",
        "community_path": "Community 文件夹",
        "no_addons":      "未找到插件。",
        "addon_ok":       "正常",
        "addon_errors":   "错误",
        "missing_fields": "缺少字段",
        "invalid_json":   "无效 JSON",
        "no_events":      "未找到事件。",
        "no_symlinks":    "没有损坏的符号链接。",
        "theme":          "主题",
        "language":       "语言",
        "light":          "浅色",
        "dark":           "深色",
        "not_detected":   "未检测到",
    },
    "JA": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "ダッシュボード",
        "tab_addons":     "アドオン",
        "tab_eventlogs":  "イベントログ",
        "tab_symlinks":   "シンボリックリンク",
        "tab_settings":   "設定",
        "run_diagnostic": "診断を実行",
        "msfs_version":   "MSFSバージョン",
        "community_path": "Communityフォルダ",
        "no_addons":      "アドオンが見つかりません。",
        "addon_ok":       "OK",
        "addon_errors":   "エラー",
        "missing_fields": "不足フィールド",
        "invalid_json":   "無効なJSON",
        "no_events":      "イベントが見つかりません。",
        "no_symlinks":    "壊れたシンボリックリンクなし。",
        "theme":          "テーマ",
        "language":       "言語",
        "light":          "ライト",
        "dark":           "ダーク",
        "not_detected":   "検出されません",
    },
    "KO": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "대시보드",
        "tab_addons":     "애드온",
        "tab_eventlogs":  "이벤트 로그",
        "tab_symlinks":   "심볼릭 링크",
        "tab_settings":   "설정",
        "run_diagnostic": "진단 실행",
        "msfs_version":   "MSFS 버전",
        "community_path": "Community 폴더",
        "no_addons":      "애드온을 찾을 수 없습니다.",
        "addon_ok":       "OK",
        "addon_errors":   "오류",
        "missing_fields": "누락된 필드",
        "invalid_json":   "잘못된 JSON",
        "no_events":      "이벤트를 찾을 수 없습니다.",
        "no_symlinks":    "끊어진 심볼릭 링크 없음.",
        "theme":          "테마",
        "language":       "언어",
        "light":          "밝게",
        "dark":           "어둡게",
        "not_detected":   "감지되지 않음",
    },
    "HI": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "डैशबोर्ड",
        "tab_addons":     "ऐड-ऑन",
        "tab_eventlogs":  "इवेंट लॉग",
        "tab_symlinks":   "सिमलिंक",
        "tab_settings":   "सेटिंग्स",
        "run_diagnostic": "डायग्नोस्टिक चलाएं",
        "msfs_version":   "MSFS संस्करण",
        "community_path": "Community फ़ोल्डर",
        "no_addons":      "कोई ऐड-ऑन नहीं मिला।",
        "addon_ok":       "ठीक है",
        "addon_errors":   "त्रुटियाँ",
        "missing_fields": "अनुपस्थित फ़ील्ड",
        "invalid_json":   "अमान्य JSON",
        "no_events":      "कोई इवेंट नहीं मिला।",
        "no_symlinks":    "कोई टूटा हुआ सिमलिंक नहीं।",
        "theme":          "थीम",
        "language":       "भाषा",
        "light":          "हल्का",
        "dark":           "गहरा",
        "not_detected":   "पता नहीं चला",
    },
    "AR": {
        "app_title":      "MSFSDiag",
        "tab_dashboard":  "لوحة التحكم",
        "tab_addons":     "إضافات",
        "tab_eventlogs":  "سجلات الأحداث",
        "tab_symlinks":   "الروابط الرمزية",
        "tab_settings":   "الإعدادات",
        "run_diagnostic": "تشغيل التشخيص",
        "msfs_version":   "إصدار MSFS",
        "community_path": "مجلد Community",
        "no_addons":      "لم يتم العثور على إضافات.",
        "addon_ok":       "OK",
        "addon_errors":   "أخطاء",
        "missing_fields": "حقول مفقودة",
        "invalid_json":   "JSON غير صالح",
        "no_events":      "لم يتم العثور على أحداث.",
        "no_symlinks":    "لا توجد روابط رمزية معطوبة.",
        "theme":          "السمة",
        "language":       "اللغة",
        "light":          "فاتح",
        "dark":           "داكن",
        "not_detected":   "غير مكتشف",
    },
}
