# ==== Imports ==== #
from pathlib import Path
import os

# ==== Application Metadata ==== #
APP_NAME    = "MSFSDiag"
APP_VERSION = "1.0.0"

# ==== MSFS Paths ==== #
MSFS2020_APPDATA: Path = Path(os.environ["APPDATA"]) / "Microsoft Flight Simulator"
MSFS2024_APPDATA_STEAM: Path = Path(os.environ["APPDATA"]) / "Microsoft Flight Simulator 2024"
MSFS2024_APPDATA_STORE: Path = Path(os.environ["LOCALAPPDATA"]) / "Packages" / "Microsoft.Limitless_8wekyb3d8bbwe" / "LocalCache"

# ==== Known Configuration Files ==== #
MSFS2020_USER_CFG: Path = MSFS2020_APPDATA / "UserCfg.opt"
MSFS2024_USER_CFG_STEAM: Path = MSFS2024_APPDATA_STEAM / "UserCfg.opt"
MSFS2024_USER_CFG_STORE: Path = MSFS2024_APPDATA_STORE / "UserCfg.opt"

# ==== Add-ons Manifest ==== #
MANIFEST_FILENAME        = "manifest.json"
LAYOUT_FILENAME          = "layout.json"
REQUIRED_MANIFEST_FIELDS = [
    "title",
    "manufacturer",
    "minimum_game_version",
    "content_type",
    "dependencies",
]

# ==== Languages ==== #
LANGUAGES = {
    "PT": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Menu Principal",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Registos de Eventos",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Definições",
        "run_diagnostic":                  "Executar Diagnóstico",
        "msfs_version":                    "Versão MSFS",
        "community_path":                  "Community Folder",
        "no_addons":                       "Nenhum add-on encontrado.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Erros",
        "addon_warning":                   "Atenção! Alguns mods com erros podem funcionar na mesma!",
        "missing_fields":                  "Campos em falta",
        "invalid_json":                    "JSON inválido",
        "no_events":                       "Nenhum evento encontrado.",
        "no_symlinks":                     "Nenhum symlink quebrado.",
        "theme":                           "Tema",
        "language":                        "Língua",
        "light":                           "Claro",
        "dark":                            "Escuro",
        "not_detected":                    "Não detetado",
        "filter_all":                      "Todos",
        "filter_ok":                       "OK",
        "filter_errors":                   "Erros",
        "filter_no_manifest":              "Sem Manifest",
        "filter_no_layout":                "Sem Layout",
        "filter_invalid_json":             "JSON Inválido",
        "filter_missing_title":            "Sem Título",
        "filter_missing_manufacturer":     "Sem Fabricante",
        "filter_missing_min_game_version": "Sem Versão Mínima",
        "filter_missing_content_type":     "Sem Tipo de Conteúdo",
        "filter_missing_dependencies":     "Sem Dependências",
    },
    "EN": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Dashboard",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Event Logs",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Settings",
        "run_diagnostic":                  "Run Diagnostic",
        "msfs_version":                    "MSFS Version",
        "community_path":                  "Community Folder",
        "no_addons":                       "No add-ons found.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Errors",
        "addon_warning":                   "Warning! Some mods with errors may still work!",
        "missing_fields":                  "Missing fields",
        "invalid_json":                    "Invalid JSON",
        "no_events":                       "No events found.",
        "no_symlinks":                     "No broken symlinks.",
        "theme":                           "Theme",
        "language":                        "Language",
        "light":                           "Light",
        "dark":                            "Dark",
        "not_detected":                    "Not detected",
        "filter_all":                      "All",
        "filter_ok":                       "OK",
        "filter_errors":                   "Errors",
        "filter_no_manifest":              "No Manifest",
        "filter_no_layout":                "No Layout",
        "filter_invalid_json":             "Invalid JSON",
        "filter_missing_title":            "No Title",
        "filter_missing_manufacturer":     "No Manufacturer",
        "filter_missing_min_game_version": "No Min. Game Version",
        "filter_missing_content_type":     "No Content Type",
        "filter_missing_dependencies":     "No Dependencies",
    },
    "ES": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Dashboard",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Registros de eventos",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Ajustes",
        "run_diagnostic":                  "Ejecutar diagnóstico",
        "msfs_version":                    "Versión MSFS",
        "community_path":                  "Carpeta Community",
        "no_addons":                       "No se encontraron add-ons.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Errores",
        "addon_warning":                   "¡Atención! ¡Algunos mods con errores pueden funcionar igual!",
        "missing_fields":                  "Campos faltantes",
        "invalid_json":                    "JSON inválido",
        "no_events":                       "No se encontraron eventos.",
        "no_symlinks":                     "No hay symlinks rotos.",
        "theme":                           "Tema",
        "language":                        "Idioma",
        "light":                           "Claro",
        "dark":                            "Oscuro",
        "not_detected":                    "No detectado",
        "filter_all":                      "Todos",
        "filter_ok":                       "OK",
        "filter_errors":                   "Errores",
        "filter_no_manifest":              "Sin Manifest",
        "filter_no_layout":                "Sin Layout",
        "filter_invalid_json":             "JSON Inválido",
        "filter_missing_title":            "Sin Título",
        "filter_missing_manufacturer":     "Sin Fabricante",
        "filter_missing_min_game_version": "Sin Versión Mínima",
        "filter_missing_content_type":     "Sin Tipo de Contenido",
        "filter_missing_dependencies":     "Sin Dependencias",
    },
    "FR": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Tableau de bord",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Journaux d'événements",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Paramètres",
        "run_diagnostic":                  "Lancer le diagnostic",
        "msfs_version":                    "Version MSFS",
        "community_path":                  "Dossier Community",
        "no_addons":                       "Aucun add-on trouvé.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Erreurs",
        "addon_warning":                   "Attention! Certains mods avec des erreurs peuvent encore fonctionner!",
        "missing_fields":                  "Champs manquants",
        "invalid_json":                    "JSON invalide",
        "no_events":                       "Aucun événement trouvé.",
        "no_symlinks":                     "Aucun symlink cassé.",
        "theme":                           "Thème",
        "language":                        "Langue",
        "light":                           "Clair",
        "dark":                            "Sombre",
        "not_detected":                    "Non détecté",
        "filter_all":                      "Tous",
        "filter_ok":                       "OK",
        "filter_errors":                   "Erreurs",
        "filter_no_manifest":              "Sans Manifest",
        "filter_no_layout":                "Sans Layout",
        "filter_invalid_json":             "JSON Invalide",
        "filter_missing_title":            "Sans Titre",
        "filter_missing_manufacturer":     "Sans Fabricant",
        "filter_missing_min_game_version": "Sans Version Minimale",
        "filter_missing_content_type":     "Sans Type de Contenu",
        "filter_missing_dependencies":     "Sans Dépendances",
    },
    "DE": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Dashboard",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Ereignisprotokolle",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Einstellungen",
        "run_diagnostic":                  "Diagnose starten",
        "msfs_version":                    "MSFS-Version",
        "community_path":                  "Community-Ordner",
        "no_addons":                       "Keine Add-ons gefunden.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Fehler",
        "addon_warning":                   "Achtung! Einige Mods mit Fehlern können trotzdem funktionieren!",
        "missing_fields":                  "Fehlende Felder",
        "invalid_json":                    "Ungültiges JSON",
        "no_events":                       "Keine Ereignisse gefunden.",
        "no_symlinks":                     "Keine defekten Symlinks.",
        "theme":                           "Thema",
        "language":                        "Sprache",
        "light":                           "Hell",
        "dark":                            "Dunkel",
        "not_detected":                    "Nicht erkannt",
        "filter_all":                      "Alle",
        "filter_ok":                       "OK",
        "filter_errors":                   "Fehler",
        "filter_no_manifest":              "Kein Manifest",
        "filter_no_layout":                "Kein Layout",
        "filter_invalid_json":             "Ungültiges JSON",
        "filter_missing_title":            "Kein Titel",
        "filter_missing_manufacturer":     "Kein Hersteller",
        "filter_missing_min_game_version": "Keine Mindestversion",
        "filter_missing_content_type":     "Kein Inhaltstyp",
        "filter_missing_dependencies":     "Keine Abhängigkeiten",
    },
    "IT": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Dashboard",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Registro eventi",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Impostazioni",
        "run_diagnostic":                  "Esegui diagnostica",
        "msfs_version":                    "Versione MSFS",
        "community_path":                  "Cartella Community",
        "no_addons":                       "Nessun add-on trovato.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Errori",
        "addon_warning":                   "Attenzione! Alcuni mod con errori potrebbero funzionare lo stesso!",
        "missing_fields":                  "Campi mancanti",
        "invalid_json":                    "JSON non valido",
        "no_events":                       "Nessun evento trovato.",
        "no_symlinks":                     "Nessun symlink rotto.",
        "theme":                           "Tema",
        "language":                        "Lingua",
        "light":                           "Chiaro",
        "dark":                            "Scuro",
        "not_detected":                    "Non rilevato",
        "filter_all":                      "Tutti",
        "filter_ok":                       "OK",
        "filter_errors":                   "Errori",
        "filter_no_manifest":              "Senza Manifest",
        "filter_no_layout":                "Senza Layout",
        "filter_invalid_json":             "JSON Non Valido",
        "filter_missing_title":            "Senza Titolo",
        "filter_missing_manufacturer":     "Senza Produttore",
        "filter_missing_min_game_version": "Senza Versione Minima",
        "filter_missing_content_type":     "Senza Tipo Contenuto",
        "filter_missing_dependencies":     "Senza Dipendenze",
    },
    "NL": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Dashboard",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Gebeurtenislogboeken",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Instellingen",
        "run_diagnostic":                  "Diagnose uitvoeren",
        "msfs_version":                    "MSFS-versie",
        "community_path":                  "Community-map",
        "no_addons":                       "Geen add-ons gevonden.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Fouten",
        "addon_warning":                   "Let op! Sommige mods met fouten kunnen toch werken!",
        "missing_fields":                  "Ontbrekende velden",
        "invalid_json":                    "Ongeldige JSON",
        "no_events":                       "Geen gebeurtenissen gevonden.",
        "no_symlinks":                     "Geen gebroken symlinks.",
        "theme":                           "Thema",
        "language":                        "Taal",
        "light":                           "Licht",
        "dark":                            "Donker",
        "not_detected":                    "Niet gedetecteerd",
        "filter_all":                      "Alle",
        "filter_ok":                       "OK",
        "filter_errors":                   "Fouten",
        "filter_no_manifest":              "Geen Manifest",
        "filter_no_layout":                "Geen Layout",
        "filter_invalid_json":             "Ongeldige JSON",
        "filter_missing_title":            "Geen Titel",
        "filter_missing_manufacturer":     "Geen Fabrikant",
        "filter_missing_min_game_version": "Geen Minimale Versie",
        "filter_missing_content_type":     "Geen Inhoudstype",
        "filter_missing_dependencies":     "Geen Afhankelijkheden",
    },
    "RU": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Панель",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Журнал событий",
        "tab_symlinks":                    "Симлинки",
        "tab_settings":                    "Настройки",
        "run_diagnostic":                  "Запустить диагностику",
        "msfs_version":                    "Версия MSFS",
        "community_path":                  "Папка Community",
        "no_addons":                       "Add-ons не найдены.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Ошибки",
        "addon_warning":                   "Внимание! Некоторые моды с ошибками могут всё равно работать!",
        "missing_fields":                  "Отсутствующие поля",
        "invalid_json":                    "Неверный JSON",
        "no_events":                       "События не найдены.",
        "no_symlinks":                     "Сломанных симлинков нет.",
        "theme":                           "Тема",
        "language":                        "Язык",
        "light":                           "Светлая",
        "dark":                            "Тёмная",
        "not_detected":                    "Не обнаружено",
        "filter_all":                      "Все",
        "filter_ok":                       "OK",
        "filter_errors":                   "Ошибки",
        "filter_no_manifest":              "Нет манифеста",
        "filter_no_layout":                "Нет макета",
        "filter_invalid_json":             "Неверный JSON",
        "filter_missing_title":            "Нет названия",
        "filter_missing_manufacturer":     "Нет производителя",
        "filter_missing_min_game_version": "Нет мин. версии",
        "filter_missing_content_type":     "Нет типа контента",
        "filter_missing_dependencies":     "Нет зависимостей",
    },
    "TR": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "Gösterge Paneli",
        "tab_addons":                      "Add-ons",
        "tab_eventlogs":                   "Olay Günlükleri",
        "tab_symlinks":                    "Symlinks",
        "tab_settings":                    "Ayarlar",
        "run_diagnostic":                  "Tanılamayı Çalıştır",
        "msfs_version":                    "MSFS Sürümü",
        "community_path":                  "Community Klasörü",
        "no_addons":                       "Add-on bulunamadı.",
        "addon_ok":                        "OK",
        "addon_errors":                    "Hatalar",
        "addon_warning":                   "Dikkat! Hatalı bazı modlar yine de çalışabilir!",
        "missing_fields":                  "Eksik alanlar",
        "invalid_json":                    "Geçersiz JSON",
        "no_events":                       "Olay bulunamadı.",
        "no_symlinks":                     "Kırık symlink yok.",
        "theme":                           "Tema",
        "language":                        "Dil",
        "light":                           "Açık",
        "dark":                            "Koyu",
        "not_detected":                    "Algılanmadı",
        "filter_all":                      "Tümü",
        "filter_ok":                       "OK",
        "filter_errors":                   "Hatalar",
        "filter_no_manifest":              "Manifest Yok",
        "filter_no_layout":                "Layout Yok",
        "filter_invalid_json":             "Geçersiz JSON",
        "filter_missing_title":            "Başlık Yok",
        "filter_missing_manufacturer":     "Üretici Yok",
        "filter_missing_min_game_version": "Min. Sürüm Yok",
        "filter_missing_content_type":     "İçerik Türü Yok",
        "filter_missing_dependencies":     "Bağımlılık Yok",
    },
    "ZH": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "仪表板",
        "tab_addons":                      "插件",
        "tab_eventlogs":                   "事件日志",
        "tab_symlinks":                    "符号链接",
        "tab_settings":                    "设置",
        "run_diagnostic":                  "运行诊断",
        "msfs_version":                    "MSFS 版本",
        "community_path":                  "Community 文件夹",
        "no_addons":                       "未找到插件。",
        "addon_ok":                        "正常",
        "addon_errors":                    "错误",
        "addon_warning":                   "注意！某些有错误的模组仍然可能正常运行！",
        "missing_fields":                  "缺少字段",
        "invalid_json":                    "无效 JSON",
        "no_events":                       "未找到事件。",
        "no_symlinks":                     "没有损坏的符号链接。",
        "theme":                           "主题",
        "language":                        "语言",
        "light":                           "浅色",
        "dark":                            "深色",
        "not_detected":                    "未检测到",
        "filter_all":                      "全部",
        "filter_ok":                       "正常",
        "filter_errors":                   "错误",
        "filter_no_manifest":              "无 Manifest",
        "filter_no_layout":                "无 Layout",
        "filter_invalid_json":             "无效 JSON",
        "filter_missing_title":            "无标题",
        "filter_missing_manufacturer":     "无制造商",
        "filter_missing_min_game_version": "无最低版本",
        "filter_missing_content_type":     "无内容类型",
        "filter_missing_dependencies":     "无依赖项",
    },
    "JA": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "ダッシュボード",
        "tab_addons":                      "アドオン",
        "tab_eventlogs":                   "イベントログ",
        "tab_symlinks":                    "シンボリックリンク",
        "tab_settings":                    "設定",
        "run_diagnostic":                  "診断を実行",
        "msfs_version":                    "MSFSバージョン",
        "community_path":                  "Communityフォルダ",
        "no_addons":                       "アドオンが見つかりません。",
        "addon_ok":                        "OK",
        "addon_errors":                    "エラー",
        "addon_warning":                   "注意！エラーのある一部のMODは正常に動作する場合があります！",
        "missing_fields":                  "不足フィールド",
        "invalid_json":                    "無効なJSON",
        "no_events":                       "イベントが見つかりません。",
        "no_symlinks":                     "壊れたシンボリックリンクなし。",
        "theme":                           "テーマ",
        "language":                        "言語",
        "light":                           "ライト",
        "dark":                            "ダーク",
        "not_detected":                    "検出されません",
        "filter_all":                      "すべて",
        "filter_ok":                       "OK",
        "filter_errors":                   "エラー",
        "filter_no_manifest":              "マニフェストなし",
        "filter_no_layout":                "レイアウトなし",
        "filter_invalid_json":             "無効なJSON",
        "filter_missing_title":            "タイトルなし",
        "filter_missing_manufacturer":     "製造元なし",
        "filter_missing_min_game_version": "最低バージョンなし",
        "filter_missing_content_type":     "コンテンツタイプなし",
        "filter_missing_dependencies":     "依存関係なし",
    },
    "KO": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "대시보드",
        "tab_addons":                      "애드온",
        "tab_eventlogs":                   "이벤트 로그",
        "tab_symlinks":                    "심볼릭 링크",
        "tab_settings":                    "설정",
        "run_diagnostic":                  "진단 실행",
        "msfs_version":                    "MSFS 버전",
        "community_path":                  "Community 폴더",
        "no_addons":                       "애드온을 찾을 수 없습니다.",
        "addon_ok":                        "OK",
        "addon_errors":                    "오류",
        "addon_warning":                   "주의! 오류가 있는 일부 모드는 여전히 작동할 수 있습니다!",
        "missing_fields":                  "누락된 필드",
        "invalid_json":                    "잘못된 JSON",
        "no_events":                       "이벤트를 찾을 수 없습니다.",
        "no_symlinks":                     "끊어진 심볼릭 링크 없음.",
        "theme":                           "테마",
        "language":                        "언어",
        "light":                           "밝게",
        "dark":                            "어둡게",
        "not_detected":                    "감지되지 않음",
        "filter_all":                      "전체",
        "filter_ok":                       "OK",
        "filter_errors":                   "오류",
        "filter_no_manifest":              "매니페스트 없음",
        "filter_no_layout":                "레이아웃 없음",
        "filter_invalid_json":             "잘못된 JSON",
        "filter_missing_title":            "제목 없음",
        "filter_missing_manufacturer":     "제조사 없음",
        "filter_missing_min_game_version": "최소 버전 없음",
        "filter_missing_content_type":     "콘텐츠 유형 없음",
        "filter_missing_dependencies":     "종속성 없음",
    },
    "HI": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "डैशबोर्ड",
        "tab_addons":                      "ऐड-ऑन",
        "tab_eventlogs":                   "इवेंट लॉग",
        "tab_symlinks":                    "सिमलिंक",
        "tab_settings":                    "सेटिंग्स",
        "run_diagnostic":                  "डायग्नोस्टिक चलाएं",
        "msfs_version":                    "MSFS संस्करण",
        "community_path":                  "Community फ़ोल्डर",
        "no_addons":                       "कोई ऐड-ऑन नहीं मिला।",
        "addon_ok":                        "ठीक है",
        "addon_errors":                    "त्रुटियाँ",
        "addon_warning":                   "ध्यान दें! कुछ त्रुटि वाले मॉड फिर भी काम कर सकते हैं!",
        "missing_fields":                  "अनुपस्थित फ़ील्ड",
        "invalid_json":                    "अमान्य JSON",
        "no_events":                       "कोई इवेंट नहीं मिला।",
        "no_symlinks":                     "कोई टूटा हुआ सिमलिंक नहीं।",
        "theme":                           "थीम",
        "language":                        "भाषा",
        "light":                           "हल्का",
        "dark":                            "गहरा",
        "not_detected":                    "पता नहीं चला",
        "filter_all":                      "सभी",
        "filter_ok":                       "ठीक है",
        "filter_errors":                   "त्रुटियाँ",
        "filter_no_manifest":              "मैनिफ़ेस्ट नहीं",
        "filter_no_layout":                "लेआउट नहीं",
        "filter_invalid_json":             "अमान्य JSON",
        "filter_missing_title":            "शीर्षक नहीं",
        "filter_missing_manufacturer":     "निर्माता नहीं",
        "filter_missing_min_game_version": "न्यूनतम संस्करण नहीं",
        "filter_missing_content_type":     "सामग्री प्रकार नहीं",
        "filter_missing_dependencies":     "निर्भरता नहीं",
    },
    "AR": {
        "app_title":                       "MSFSDiag",
        "tab_dashboard":                   "لوحة التحكم",
        "tab_addons":                      "إضافات",
        "tab_eventlogs":                   "سجلات الأحداث",
        "tab_symlinks":                    "الروابط الرمزية",
        "tab_settings":                    "الإعدادات",
        "run_diagnostic":                  "تشغيل التشخيص",
        "msfs_version":                    "إصدار MSFS",
        "community_path":                  "مجلد Community",
        "no_addons":                       "لم يتم العثور على إضافات.",
        "addon_ok":                        "OK",
        "addon_errors":                    "أخطاء",
        "addon_warning":                   "تحذير! بعض الإضافات التي تحتوي على أخطاء قد تعمل على أي حال!",
        "missing_fields":                  "حقول مفقودة",
        "invalid_json":                    "JSON غير صالح",
        "no_events":                       "لم يتم العثور على أحداث.",
        "no_symlinks":                     "لا توجد روابط رمزية معطوبة.",
        "theme":                           "السمة",
        "language":                        "اللغة",
        "light":                           "فاتح",
        "dark":                            "داكن",
        "not_detected":                    "غير مكتشف",
        "filter_all":                      "الكل",
        "filter_ok":                       "OK",
        "filter_errors":                   "أخطاء",
        "filter_no_manifest":              "بدون Manifest",
        "filter_no_layout":                "بدون Layout",
        "filter_invalid_json":             "JSON غير صالح",
        "filter_missing_title":            "بدون عنوان",
        "filter_missing_manufacturer":     "بدون مصنّع",
        "filter_missing_min_game_version": "بدون حد أدنى للإصدار",
        "filter_missing_content_type":     "بدون نوع المحتوى",
        "filter_missing_dependencies":     "بدون تبعيات",
    },
}
